# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Set up Docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Variable de entorno con tu nombre de usuario de Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Variable de entorno con tu contraseña de Docker Hub
          repository: southamerica-west1-docker.pkg.dev/taller-isw-2023s2/tisw  # Reemplaza con tu nombre de usuario y nombre de repositorio en Docker Hub
          tags: latest  # Puedes personalizar las etiquetas

      - name: Build and Test
        run: |
          docker build -t my-app-image .
          docker run my-app-image go test ./...

      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: southamerica-west1-docker.pkg.dev/taller-isw-2023s2/tisw
          tags: latest
