name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main  # Define la rama en la que deseas que se ejecute el flujo de trabajo

jobs:
  build:
    runs-on: ubuntu-latest  # Usa el sistema operativo Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Para clonar el repositorio

      - name: Set up Docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Variable de entorno con tu nombre de usuario de Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Variable de entorno con tu contraseña de Docker Hub
          repository: tuusuario/tu-repositorio  # Reemplaza con tu nombre de usuario y nombre de repositorio en Docker Hub
          tags: latest  # Puedes personalizar las etiquetas

      - name: Build and Test
        run: |
          docker build -t my-app-image .
          docker run my-app-image go test ./...

      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tuusuario/tu-repositorio
          tags: latest